name: TestTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27393
title: TestTest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ef3715'
    - '#fac826'
    - '#1bc7b5'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
