name: TestTest
favicon: null
layout_spectrum: 0.08954945066943765
typography_spectrum: 0.34474918525666
title: TestTest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4922763917129487
  lightness: 0.23242414090782404
  saturation: 0.18217938346788287
  rhythmicContrast: 0.9427842199802399
purpose: []
