typography_spectrum: 0.27393
color:
  brandColors:
    - '#ffffff'
    - '#ef3715'
    - '#fac826'
    - '#1bc7b5'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: TestTest
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Manul
    id: aa02228f-539a-4ead-a169-f14a499c5eed
    type: content
  - name: git
    url: 'https://github.com/the-domains/testtest'
    type: external
favicon: null
title: TestTest
content: []
description: Blubb blubb blubb
purpose:
  - type: external
    url: 'http://www.bitcraft.org'
    label: www.bitcraft.org
  - type: internal
    label: Manul!
    item: aa02228f-539a-4ead-a169-f14a499c5eed
