layout_spectrum: 0.9547363959377317
typography_spectrum: 0.148316461139792
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.3423598642374325
  lightness: 0.3995374043224066
  saturation: 0.9031260292640528
  rhythmicContrast: 0.6618446719029568
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: TestTest
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Manul
    id: aa02228f-539a-4ead-a169-f14a499c5eed
    type: content
  - name: git
    url: 'https://github.com/the-domains/testtest'
    type: external
favicon: null
title: TestTest
content: []
description: Blubb blubb blubb
purpose:
  - type: external
    url: 'http://www.bitcraft.org'
    label: www.bitcraft.org
  - type: internal
    label: Manul!
    item: aa02228f-539a-4ead-a169-f14a499c5eed
